all: 
	voc -s LINUX64.Mod
	voc -s Platformunix.Mod
	voc -s Heap.Mod
	voc -s Out.Mod
	voc -s Modules.Mod
	voc -s Args.Mod
	voc -s Console.Mod
	voc -s Reals.Mod
	voc -s Strings.Mod
	voc -s Files.Mod
	voc -s X11.Mod
	voc -s Fonts.Mod
	voc -s v4texts.Mod
	voc -s v4kernel.Mod
	voc -s v4oberon.Mod
